// This file is auto-generated by generate_AllSensors_DLHR_subclasses.h. Do not edit!

#ifndef ALLSENSORS_DLHR_SUBCLASSES_H
#define ALLSENSORS_DLHR_SUBCLASSES_H

class AllSensors_DLHR_F05D_6 : public AllSensors_DLHR {
public:
  AllSensors_DLHR_F05D_6(TwoWire *bus) : AllSensors_DLHR(bus, AllSensors_DLHR::SensorType::DIFFERENTIAL, AllSensors_DLHR::SensorResolution::RESOLUTION_16_BITS, 0.5) {}
};

class AllSensors_DLHR_F05D_7 : public AllSensors_DLHR {
public:
  AllSensors_DLHR_F05D_7(TwoWire *bus) : AllSensors_DLHR(bus, AllSensors_DLHR::SensorType::DIFFERENTIAL, AllSensors_DLHR::SensorResolution::RESOLUTION_17_BITS, 0.5) {}
};

class AllSensors_DLHR_F05D_8 : public AllSensors_DLHR {
public:
  AllSensors_DLHR_F05D_8(TwoWire *bus) : AllSensors_DLHR(bus, AllSensors_DLHR::SensorType::DIFFERENTIAL, AllSensors_DLHR::SensorResolution::RESOLUTION_18_BITS, 0.5) {}
};

class AllSensors_DLHR_F05G_6 : public AllSensors_DLHR {
public:
  AllSensors_DLHR_F05G_6(TwoWire *bus) : AllSensors_DLHR(bus, AllSensors_DLHR::SensorType::GAGE, AllSensors_DLHR::SensorResolution::RESOLUTION_16_BITS, 0.5) {}
};

class AllSensors_DLHR_F05G_7 : public AllSensors_DLHR {
public:
  AllSensors_DLHR_F05G_7(TwoWire *bus) : AllSensors_DLHR(bus, AllSensors_DLHR::SensorType::GAGE, AllSensors_DLHR::SensorResolution::RESOLUTION_17_BITS, 0.5) {}
};

class AllSensors_DLHR_F05G_8 : public AllSensors_DLHR {
public:
  AllSensors_DLHR_F05G_8(TwoWire *bus) : AllSensors_DLHR(bus, AllSensors_DLHR::SensorType::GAGE, AllSensors_DLHR::SensorResolution::RESOLUTION_18_BITS, 0.5) {}
};

class AllSensors_DLHR_L01D_6 : public AllSensors_DLHR {
public:
  AllSensors_DLHR_L01D_6(TwoWire *bus) : AllSensors_DLHR(bus, AllSensors_DLHR::SensorType::DIFFERENTIAL, AllSensors_DLHR::SensorResolution::RESOLUTION_16_BITS, 1.0) {}
};

class AllSensors_DLHR_L01D_7 : public AllSensors_DLHR {
public:
  AllSensors_DLHR_L01D_7(TwoWire *bus) : AllSensors_DLHR(bus, AllSensors_DLHR::SensorType::DIFFERENTIAL, AllSensors_DLHR::SensorResolution::RESOLUTION_17_BITS, 1.0) {}
};

class AllSensors_DLHR_L01D_8 : public AllSensors_DLHR {
public:
  AllSensors_DLHR_L01D_8(TwoWire *bus) : AllSensors_DLHR(bus, AllSensors_DLHR::SensorType::DIFFERENTIAL, AllSensors_DLHR::SensorResolution::RESOLUTION_18_BITS, 1.0) {}
};

class AllSensors_DLHR_L01G_6 : public AllSensors_DLHR {
public:
  AllSensors_DLHR_L01G_6(TwoWire *bus) : AllSensors_DLHR(bus, AllSensors_DLHR::SensorType::GAGE, AllSensors_DLHR::SensorResolution::RESOLUTION_16_BITS, 1.0) {}
};

class AllSensors_DLHR_L01G_7 : public AllSensors_DLHR {
public:
  AllSensors_DLHR_L01G_7(TwoWire *bus) : AllSensors_DLHR(bus, AllSensors_DLHR::SensorType::GAGE, AllSensors_DLHR::SensorResolution::RESOLUTION_17_BITS, 1.0) {}
};

class AllSensors_DLHR_L01G_8 : public AllSensors_DLHR {
public:
  AllSensors_DLHR_L01G_8(TwoWire *bus) : AllSensors_DLHR(bus, AllSensors_DLHR::SensorType::GAGE, AllSensors_DLHR::SensorResolution::RESOLUTION_18_BITS, 1.0) {}
};

class AllSensors_DLHR_L02D_6 : public AllSensors_DLHR {
public:
  AllSensors_DLHR_L02D_6(TwoWire *bus) : AllSensors_DLHR(bus, AllSensors_DLHR::SensorType::DIFFERENTIAL, AllSensors_DLHR::SensorResolution::RESOLUTION_16_BITS, 2.0) {}
};

class AllSensors_DLHR_L02D_7 : public AllSensors_DLHR {
public:
  AllSensors_DLHR_L02D_7(TwoWire *bus) : AllSensors_DLHR(bus, AllSensors_DLHR::SensorType::DIFFERENTIAL, AllSensors_DLHR::SensorResolution::RESOLUTION_17_BITS, 2.0) {}
};

class AllSensors_DLHR_L02D_8 : public AllSensors_DLHR {
public:
  AllSensors_DLHR_L02D_8(TwoWire *bus) : AllSensors_DLHR(bus, AllSensors_DLHR::SensorType::DIFFERENTIAL, AllSensors_DLHR::SensorResolution::RESOLUTION_18_BITS, 2.0) {}
};

class AllSensors_DLHR_L02G_6 : public AllSensors_DLHR {
public:
  AllSensors_DLHR_L02G_6(TwoWire *bus) : AllSensors_DLHR(bus, AllSensors_DLHR::SensorType::GAGE, AllSensors_DLHR::SensorResolution::RESOLUTION_16_BITS, 2.0) {}
};

class AllSensors_DLHR_L02G_7 : public AllSensors_DLHR {
public:
  AllSensors_DLHR_L02G_7(TwoWire *bus) : AllSensors_DLHR(bus, AllSensors_DLHR::SensorType::GAGE, AllSensors_DLHR::SensorResolution::RESOLUTION_17_BITS, 2.0) {}
};

class AllSensors_DLHR_L02G_8 : public AllSensors_DLHR {
public:
  AllSensors_DLHR_L02G_8(TwoWire *bus) : AllSensors_DLHR(bus, AllSensors_DLHR::SensorType::GAGE, AllSensors_DLHR::SensorResolution::RESOLUTION_18_BITS, 2.0) {}
};

class AllSensors_DLHR_L05D_6 : public AllSensors_DLHR {
public:
  AllSensors_DLHR_L05D_6(TwoWire *bus) : AllSensors_DLHR(bus, AllSensors_DLHR::SensorType::DIFFERENTIAL, AllSensors_DLHR::SensorResolution::RESOLUTION_16_BITS, 5.0) {}
};

class AllSensors_DLHR_L05D_7 : public AllSensors_DLHR {
public:
  AllSensors_DLHR_L05D_7(TwoWire *bus) : AllSensors_DLHR(bus, AllSensors_DLHR::SensorType::DIFFERENTIAL, AllSensors_DLHR::SensorResolution::RESOLUTION_17_BITS, 5.0) {}
};

class AllSensors_DLHR_L05D_8 : public AllSensors_DLHR {
public:
  AllSensors_DLHR_L05D_8(TwoWire *bus) : AllSensors_DLHR(bus, AllSensors_DLHR::SensorType::DIFFERENTIAL, AllSensors_DLHR::SensorResolution::RESOLUTION_18_BITS, 5.0) {}
};

class AllSensors_DLHR_L05G_6 : public AllSensors_DLHR {
public:
  AllSensors_DLHR_L05G_6(TwoWire *bus) : AllSensors_DLHR(bus, AllSensors_DLHR::SensorType::GAGE, AllSensors_DLHR::SensorResolution::RESOLUTION_16_BITS, 5.0) {}
};

class AllSensors_DLHR_L05G_7 : public AllSensors_DLHR {
public:
  AllSensors_DLHR_L05G_7(TwoWire *bus) : AllSensors_DLHR(bus, AllSensors_DLHR::SensorType::GAGE, AllSensors_DLHR::SensorResolution::RESOLUTION_17_BITS, 5.0) {}
};

class AllSensors_DLHR_L05G_8 : public AllSensors_DLHR {
public:
  AllSensors_DLHR_L05G_8(TwoWire *bus) : AllSensors_DLHR(bus, AllSensors_DLHR::SensorType::GAGE, AllSensors_DLHR::SensorResolution::RESOLUTION_18_BITS, 5.0) {}
};

class AllSensors_DLHR_L10D_6 : public AllSensors_DLHR {
public:
  AllSensors_DLHR_L10D_6(TwoWire *bus) : AllSensors_DLHR(bus, AllSensors_DLHR::SensorType::DIFFERENTIAL, AllSensors_DLHR::SensorResolution::RESOLUTION_16_BITS, 10.0) {}
};

class AllSensors_DLHR_L10D_7 : public AllSensors_DLHR {
public:
  AllSensors_DLHR_L10D_7(TwoWire *bus) : AllSensors_DLHR(bus, AllSensors_DLHR::SensorType::DIFFERENTIAL, AllSensors_DLHR::SensorResolution::RESOLUTION_17_BITS, 10.0) {}
};

class AllSensors_DLHR_L10D_8 : public AllSensors_DLHR {
public:
  AllSensors_DLHR_L10D_8(TwoWire *bus) : AllSensors_DLHR(bus, AllSensors_DLHR::SensorType::DIFFERENTIAL, AllSensors_DLHR::SensorResolution::RESOLUTION_18_BITS, 10.0) {}
};

class AllSensors_DLHR_L10G_6 : public AllSensors_DLHR {
public:
  AllSensors_DLHR_L10G_6(TwoWire *bus) : AllSensors_DLHR(bus, AllSensors_DLHR::SensorType::GAGE, AllSensors_DLHR::SensorResolution::RESOLUTION_16_BITS, 10.0) {}
};

class AllSensors_DLHR_L10G_7 : public AllSensors_DLHR {
public:
  AllSensors_DLHR_L10G_7(TwoWire *bus) : AllSensors_DLHR(bus, AllSensors_DLHR::SensorType::GAGE, AllSensors_DLHR::SensorResolution::RESOLUTION_17_BITS, 10.0) {}
};

class AllSensors_DLHR_L10G_8 : public AllSensors_DLHR {
public:
  AllSensors_DLHR_L10G_8(TwoWire *bus) : AllSensors_DLHR(bus, AllSensors_DLHR::SensorType::GAGE, AllSensors_DLHR::SensorResolution::RESOLUTION_18_BITS, 10.0) {}
};

class AllSensors_DLHR_L20D_6 : public AllSensors_DLHR {
public:
  AllSensors_DLHR_L20D_6(TwoWire *bus) : AllSensors_DLHR(bus, AllSensors_DLHR::SensorType::DIFFERENTIAL, AllSensors_DLHR::SensorResolution::RESOLUTION_16_BITS, 20.0) {}
};

class AllSensors_DLHR_L20D_7 : public AllSensors_DLHR {
public:
  AllSensors_DLHR_L20D_7(TwoWire *bus) : AllSensors_DLHR(bus, AllSensors_DLHR::SensorType::DIFFERENTIAL, AllSensors_DLHR::SensorResolution::RESOLUTION_17_BITS, 20.0) {}
};

class AllSensors_DLHR_L20D_8 : public AllSensors_DLHR {
public:
  AllSensors_DLHR_L20D_8(TwoWire *bus) : AllSensors_DLHR(bus, AllSensors_DLHR::SensorType::DIFFERENTIAL, AllSensors_DLHR::SensorResolution::RESOLUTION_18_BITS, 20.0) {}
};

class AllSensors_DLHR_L20G_6 : public AllSensors_DLHR {
public:
  AllSensors_DLHR_L20G_6(TwoWire *bus) : AllSensors_DLHR(bus, AllSensors_DLHR::SensorType::GAGE, AllSensors_DLHR::SensorResolution::RESOLUTION_16_BITS, 20.0) {}
};

class AllSensors_DLHR_L20G_7 : public AllSensors_DLHR {
public:
  AllSensors_DLHR_L20G_7(TwoWire *bus) : AllSensors_DLHR(bus, AllSensors_DLHR::SensorType::GAGE, AllSensors_DLHR::SensorResolution::RESOLUTION_17_BITS, 20.0) {}
};

class AllSensors_DLHR_L20G_8 : public AllSensors_DLHR {
public:
  AllSensors_DLHR_L20G_8(TwoWire *bus) : AllSensors_DLHR(bus, AllSensors_DLHR::SensorType::GAGE, AllSensors_DLHR::SensorResolution::RESOLUTION_18_BITS, 20.0) {}
};

class AllSensors_DLHR_L30D_6 : public AllSensors_DLHR {
public:
  AllSensors_DLHR_L30D_6(TwoWire *bus) : AllSensors_DLHR(bus, AllSensors_DLHR::SensorType::DIFFERENTIAL, AllSensors_DLHR::SensorResolution::RESOLUTION_16_BITS, 30.0) {}
};

class AllSensors_DLHR_L30D_7 : public AllSensors_DLHR {
public:
  AllSensors_DLHR_L30D_7(TwoWire *bus) : AllSensors_DLHR(bus, AllSensors_DLHR::SensorType::DIFFERENTIAL, AllSensors_DLHR::SensorResolution::RESOLUTION_17_BITS, 30.0) {}
};

class AllSensors_DLHR_L30D_8 : public AllSensors_DLHR {
public:
  AllSensors_DLHR_L30D_8(TwoWire *bus) : AllSensors_DLHR(bus, AllSensors_DLHR::SensorType::DIFFERENTIAL, AllSensors_DLHR::SensorResolution::RESOLUTION_18_BITS, 30.0) {}
};

class AllSensors_DLHR_L30G_6 : public AllSensors_DLHR {
public:
  AllSensors_DLHR_L30G_6(TwoWire *bus) : AllSensors_DLHR(bus, AllSensors_DLHR::SensorType::GAGE, AllSensors_DLHR::SensorResolution::RESOLUTION_16_BITS, 30.0) {}
};

class AllSensors_DLHR_L30G_7 : public AllSensors_DLHR {
public:
  AllSensors_DLHR_L30G_7(TwoWire *bus) : AllSensors_DLHR(bus, AllSensors_DLHR::SensorType::GAGE, AllSensors_DLHR::SensorResolution::RESOLUTION_17_BITS, 30.0) {}
};

class AllSensors_DLHR_L30G_8 : public AllSensors_DLHR {
public:
  AllSensors_DLHR_L30G_8(TwoWire *bus) : AllSensors_DLHR(bus, AllSensors_DLHR::SensorType::GAGE, AllSensors_DLHR::SensorResolution::RESOLUTION_18_BITS, 30.0) {}
};

class AllSensors_DLHR_L60D_6 : public AllSensors_DLHR {
public:
  AllSensors_DLHR_L60D_6(TwoWire *bus) : AllSensors_DLHR(bus, AllSensors_DLHR::SensorType::DIFFERENTIAL, AllSensors_DLHR::SensorResolution::RESOLUTION_16_BITS, 60.0) {}
};

class AllSensors_DLHR_L60D_7 : public AllSensors_DLHR {
public:
  AllSensors_DLHR_L60D_7(TwoWire *bus) : AllSensors_DLHR(bus, AllSensors_DLHR::SensorType::DIFFERENTIAL, AllSensors_DLHR::SensorResolution::RESOLUTION_17_BITS, 60.0) {}
};

class AllSensors_DLHR_L60D_8 : public AllSensors_DLHR {
public:
  AllSensors_DLHR_L60D_8(TwoWire *bus) : AllSensors_DLHR(bus, AllSensors_DLHR::SensorType::DIFFERENTIAL, AllSensors_DLHR::SensorResolution::RESOLUTION_18_BITS, 60.0) {}
};

class AllSensors_DLHR_L60G_6 : public AllSensors_DLHR {
public:
  AllSensors_DLHR_L60G_6(TwoWire *bus) : AllSensors_DLHR(bus, AllSensors_DLHR::SensorType::GAGE, AllSensors_DLHR::SensorResolution::RESOLUTION_16_BITS, 60.0) {}
};

class AllSensors_DLHR_L60G_7 : public AllSensors_DLHR {
public:
  AllSensors_DLHR_L60G_7(TwoWire *bus) : AllSensors_DLHR(bus, AllSensors_DLHR::SensorType::GAGE, AllSensors_DLHR::SensorResolution::RESOLUTION_17_BITS, 60.0) {}
};

class AllSensors_DLHR_L60G_8 : public AllSensors_DLHR {
public:
  AllSensors_DLHR_L60G_8(TwoWire *bus) : AllSensors_DLHR(bus, AllSensors_DLHR::SensorType::GAGE, AllSensors_DLHR::SensorResolution::RESOLUTION_18_BITS, 60.0) {}
};

#endif // ALLSENSORS_DLHR_SUBCLASSES_H
